receivers:
  otlp:
    protocols:
      #grpc:
        #endpoint: otel-collector:4317
      #http:
        #endpoint: otel-collector:4318
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

exporters:
  debug:
    verbosity: detailed

  prometheus:
    endpoint: otel-collector:8889
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

  otlphttp:
    endpoint: "http://loki:3100/otlp"
    tls:
      insecure: true


processors:
  batch:

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp,  debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, debug]