global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
  # remember that node exporter needs fair amount of permissions to run on the host machine 
  # so we need to run it in the host e.g running as root check Stuart's blog for more info
    static_configs:
      - targets: ['node_exporter:9100']
  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']