// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Person.Infrastructure;

#nullable disable

namespace Person.Infrastructure.Migrations
{
    [DbContext(typeof(PersonDbContext))]
    partial class PersonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Person.Domain.Entities.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonTypeId")
                        .HasColumnType("int");

                    b.HasKey("PersonId");

                    b.HasIndex("PersonTypeId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            Age = 30,
                            Name = "John Doe",
                            PersonTypeId = 1
                        },
                        new
                        {
                            PersonId = 2,
                            Age = 25,
                            Name = "Jane Smith",
                            PersonTypeId = 2
                        },
                        new
                        {
                            PersonId = 3,
                            Age = 28,
                            Name = "Alice Johnson",
                            PersonTypeId = 1
                        },
                        new
                        {
                            PersonId = 4,
                            Age = 22,
                            Name = "Bob Brown",
                            PersonTypeId = 2
                        },
                        new
                        {
                            PersonId = 5,
                            Age = 35,
                            Name = "Carol White",
                            PersonTypeId = 1
                        },
                        new
                        {
                            PersonId = 6,
                            Age = 20,
                            Name = "David Black",
                            PersonTypeId = 2
                        },
                        new
                        {
                            PersonId = 7,
                            Age = 27,
                            Name = "Eve Green",
                            PersonTypeId = 1
                        },
                        new
                        {
                            PersonId = 8,
                            Age = 23,
                            Name = "Frank Blue",
                            PersonTypeId = 2
                        },
                        new
                        {
                            PersonId = 9,
                            Age = 32,
                            Name = "Grace Red",
                            PersonTypeId = 1
                        },
                        new
                        {
                            PersonId = 10,
                            Age = 21,
                            Name = "Henry Yellow",
                            PersonTypeId = 2
                        });
                });

            modelBuilder.Entity("Person.Domain.Entities.PersonType", b =>
                {
                    b.Property<int>("PersonTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonTypeId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonTypeId");

                    b.ToTable("PersonTypes");

                    b.HasData(
                        new
                        {
                            PersonTypeId = 1,
                            Description = "Teacher"
                        },
                        new
                        {
                            PersonTypeId = 2,
                            Description = "Student"
                        });
                });

            modelBuilder.Entity("Person.Domain.Entities.Person", b =>
                {
                    b.HasOne("Person.Domain.Entities.PersonType", "PersonType")
                        .WithMany()
                        .HasForeignKey("PersonTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonType");
                });
#pragma warning restore 612, 618
        }
    }
}
